wandb_version: 1

BASE_DATA_PATH:
  desc: null
  value: /opt/ml/input/data
PROJECT_PATH:
  desc: null
  value: /opt/ml/p3-ims-obd-savetheearth
_wandb:
  desc: null
  value:
    cli_version: 0.10.27
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      4: 3.7.7
      5: 0.10.27
      8:
      - 5
batch_size:
  desc: null
  value: 8
coco_train_json:
  desc: null
  value: train.json
coco_val_json:
  desc: null
  value: val.json
criterion:
  desc: null
  value: cross_entropy
description:
  desc: null
  value: deconvnet_first
kfold:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 0.0001
model:
  desc: null
  value: Deconvnet_vgg
model_save_name:
  desc: null
  value: deconvnet__model.pt
nepochs:
  desc: null
  value: 10
num_workers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: Adam
patience:
  desc: null
  value: 5
print_freq:
  desc: null
  value: 1
resize_height:
  desc: null
  value: 512
resize_width:
  desc: null
  value: 512
scheduler:
  desc: null
  value: StepLR
seed:
  desc: null
  value: 42
train_augmentation:
  desc: null
  value: BaseTrainAugmentation
val_augmentation:
  desc: null
  value: BaseTrainAugmentation
